In [5]:
import torch 
import torch.nn as nn
import numpy as np

In [2]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print('softmax numpy:', outputs)

softmax numpy: [0.65900114 0.24243297 0.09856589]


In [3]:
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0)
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [4]:
def cross_entropy(actual, predicted):
    loss = -np.sum(actual * np.log(predicted))
    return loss
Y = np.array([1, 0, 0])
Y_g = np.array([0.7, 0.2, 0.1])
Y_b = np.array([0.1, 0.3, 0.6])
l1 = cross_entropy(Y, Y_g)
l2 = cross_entropy(Y, Y_b)
print(l1, l2)

0.35667494393873245 2.3025850929940455


In [9]:
loss = nn.CrossEntropyLoss()

Y = torch.tensor([0])
# nsamples x nclasses = 1 x 3
Y_g =  torch.tensor([[10.0, 2.0, 0.1]])
Y_b = torch.tensor([[0.1, 99.0, 99.0]])

l1 = loss(Y_g, Y)
l2 = loss(Y_b, Y)

print(l1.item())
print(l2.item())

_, predictions1 = torch.max(Y_g, 1)
_, predictions2 = torch.max(Y_b, 1)
print(predictions1)
print(predictions2)

0.00038556772051379085
99.59314727783203
tensor([0])
tensor([1])


In [11]:
Y = torch.tensor([2, 0, 1])

# nsamples x nclasses = 3 x 3
Y_g = torch.tensor([[0.1, 1.0, 2.1], [2.1, 1.0, 0.1], [0.1, 2.0, 0.1]])
Y_b = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 0.1, 2.1]])

l1 = loss(Y_g, Y)
l2 = loss(Y_b, Y)

print(l1.item())
print(l2.item())

_, predictions1 = torch.max(Y_g, 1)
_, predictions2 = torch.max(Y_b, 1)
print(predictions1)
print(predictions2)

0.34326112270355225
2.3358757495880127
tensor([2, 0, 1])
tensor([0, 2, 2])
